### ISSUE TITLE
set ProductCode

### ISSUE THREAD

**Issue by irzyxel** [windirstat/windirstat#8] opened 2024-01-24 23:38 UTC
windirstat doesnt show its version when using winget.
set ProductCode to identify installed version and make easy updates possible.

PS C:\Users\Michael> winget upgrade --include-unknown
Name                                           ID                                       Version      Verfügbar     Quelle
-----------------------------------------------------------------------------------------------------------------------
WinDirStat 1.1.2                         WinDirStat.WinDirStat          Unknown      1.1.2         winget

**Comment by assarbad** [comment] 2024-01-28 21:05
Duplicate of #2 and #3

**Closed by assarbad** 2024-01-28 21:05 UTC
