### ISSUE TITLE
Assertion when run as Admin and unticked "Skip protected (hidden&system)" 

### ISSUE THREAD

**Issue by RobertK66** [windirstat/windirstat#23] opened 2024-02-25 07:40 UTC
I try to minimize the 'Unknown" line in the result. 

So I start the Application elevated (either by restart elevated or by starting VS in Admin mode). Then I remove the tick from "Geschützte Elemente überspringen (Verstecktes & System)" and scan my Windows drive. It finalizes the scan and when the Gui builds up it runs into this assertion:

![image](https://github.com/windirstat/windirstat/assets/16986510/3ff72aec-f679-41be-a5ba-4770c76c1979)

**Comment by NoMoreFood** [comment] 2024-02-26 21:04
Verified reproducible.  Caused by the cumulative individual allocations being larger than what the volume is being reported as being used (total - free).  Investigating cause...

**Comment by NoMoreFood** [comment] 2024-10-22 15:00
Since this immediate issue is resolved, going to close this ticket.  Will consider opening a new issue as an enhancement for hardlink detection.

**Closed by NoMoreFood** 2024-10-22 15:00 UTC
Labels: bug
