### ISSUE TITLE
[bug] "subst" Confusion

### ISSUE THREAD

**Issue by salvis** [windirstat/windirstat#127] opened 2024-11-04 16:03 UTC
Version 2.0.3 is confused by drive letters created with the "subst" command.

Example: My F: drive points to a directory deep down in the directory structure of my C: drive, but WinDirStat displays F: as a separate drive on the Select Drives dialog, with all properties (name, size, used) identical to the C: drive, but it can't do anything with it, when I select it as a an Individual Drive.

When I select All Local Drives, WinDirStat ignores the F: drive.

**Comment by NoMoreFood** [comment] 2024-11-05 01:11
It reporting as the same general statistics does not surprise me, but I think I would expect it to do something when you manually select it.  I will look into this.

**Comment by salvis** [comment] 2024-11-05 08:39
> It reporting as the same general statistics does not surprise me,

IMHO, it should not look like a normal internal drive. It would be even more confusing if it continued to look like a normal drive but with different numbers, like only the sizes of the directory subtree.

Network drives, external USB drives, SD cards all have different icons, I think "subst" drives should also have a different icon and should include a reference to their host drive letter, something like "(F: on C:)". I have a habit of putting the drive letter into the volume label, which helps me to avoid catastrophic errors:

![image](https://github.com/user-attachments/assets/74b8394d-5852-4dab-8cb0-ee823d4150fd)

BTW, NTFS-formatted memory sticks mounted with caching enabled (my G: drive) have the same icon as internal drives. Could they also get a different icon? Or should they get the same icon as the external USB hard drive M:?

**Comment by NoMoreFood** [comment] 2024-11-05 09:51
I think I found the reason it wasn't scanning and am making a change to accommodate it.  I do agree that these things ought to have different icons, but it's pulling them directly from Windows.  If we can get Microsoft to change it, WinDirStat will reflect that :-)

**Comment by NoMoreFood** [comment] 2024-11-06 07:43
Can you see if this version addresses it not scanning properly when you click on it?  

https://github.com/windirstat/windirstat/releases/tag/beta/v2.1.0/2024-11-06

**Comment by salvis** [comment] 2024-11-06 13:59
No, it doesn't:

![image](https://github.com/user-attachments/assets/62bd3e62-b196-4d1d-9160-617ac624888f)

**Comment by NoMoreFood** [comment] 2024-11-07 00:39
Hmm... did you launch as administrator?  Where roughly does that point on your file system?

**Comment by salvis** [comment] 2024-11-07 11:29
I'm running as restricted user on Windows 10 Pro.

![image](https://github.com/user-attachments/assets/3f543d87-2612-42b5-939f-db28db5d8b7e)

The directory has no files, only a subdirectory with more subdirectories, but ultimately, there are files inside. No hidden or system attributes, (F)ull access in cacls.

"subst" is user-specific, so F: is not there under the administrator account. However, I can create it as administrator, and then it behaves the same.

However, trying to create file inside gives me the error "The media is write protected." Apparently, Acronis (a backup application) is somehow protecting that directory. I can go inside with Windows Explorer as well as File Commander/W, but WinDirStat cannot see inside, not even when navigating via the WinDirStat directory tree starting at C:\.

When scanning, are you trying to open the directories with read/write access? I currently have 32 GB under that directory, and it would be nice to see these in WinDirStat, of course.

It's a coincidence that I have a subst'ed drive for the Acronis phone backup directory, but then again, Acronis setup accepts only a drive letter, not a directory path for its target location, which is why I'm using subst.

**Comment by NoMoreFood** [comment] 2024-11-07 11:50
No, we are not opening anything for read/write.  If you can see it in Windows Explorer, you ought to be able to see it WinDirStat unless Acronis is doing something crazy at the file system level. I'll see if I can pull down a trial of Acronis and check.

**Comment by assarbad** [comment] 2024-11-07 23:18
> "subst" is user-specific, so F: is not there under the administrator account. However, I can create it as administrator, and then it behaves the same.

Your terminology is a little off here. Since I've encounter plenty confusion in the past regarding the inner workings of this, I shall nitpick away ... I apologize up front.

Suppose you are running as normal first created user who is member of `BUILTIN\Administrators` but isn't identical to `BUILTIN\Administrator` (RID¹==500). We'll call that user `salvis` (RID >= 1000) for the discussion. In this case — subject to your particular configuration — you should run by default with the non-elevated token, but a paired elevated token exists and by creating a process through UAC elevation you can gain the same privileges that are bestowed on everyone in `BUILTIN\Administrators`.

**However, you are still `salvis`** (RID >= 1000) as you can check by starting an elevated prompt and running `whoami /all`.

But here comes the issue that causes the user-specificity you correctly point out: each and every authentication session gets its own so-called authentication ID (e.g. `_TOKEN_STATISTICS::AuthenticationId`) and that is the relevant value the NT object manager uses when looking up "DOS" device names.

For example the elevated token may have an authentication ID of `00000000-0013587d` whereas the paired un-elevated token may have `00000000-001358a5` (`\Sessions\0\DosDevices\00000000-001358a5`). Both represent the same user (the so-called principal), but each has a local device namespace of its own. **This limits visibility, but not necessarily accessibility.**

Creating a drive letter E: from elevated context creates the symlink as `\Sessions\0\DosDevices\00000000-0013587d\E:` and so it wouldn't conflict with the same drive letter getting created from the un-elevated one as `\Sessions\0\DosDevices\00000000-001358a5\E:`; but depending on the applicable lookup rules they may shadow `\GLOBAL??\E:`. There's an escape hatch on modern Windows, though. You can (from Win32) use a path such as `\??\Global\GLOBALROOT\Sessions\0\DosDevices\...` to access paths inside the respective other namespace as long as this isn't restricted by the involved security descriptors ([also see](https://googleprojectzero.blogspot.com/2016/02/the-definitive-guide-on-win32-to-nt.html)). Unfortunately `subst` filters the paths because it checks if it can access the target path, but otherwise you should technically be able to `subst F: \Sessions\0\DosDevices\00000000-0013587d\Global\GLOBALROOT\Sessions\0\DosDevices\00000000-001358a5\E:`. Obviously with `NtCreateSymbolicLinkObject` you can achieve that without `subst` imposing its own rules. But then you don't have to go through these hoops at all, because you could point any drive letter to any target path ...

![Screenshot_20241107_225244](https://github.com/user-attachments/assets/ecb22876-c9b3-4977-8203-e36b044d51c5)

You can verify these assertions yourself with a tool like WinObj from SysInternals/Microsoft or my own [ntobjx](https://sourceforge.net/projects/ntobjx/).

The following is already irrelevant due to the visibility issue incurred by the namespaces based named after authentication IDs. But I included it to give the full picture.

The main difference for the purpose of object creation and ability to access objects is that the elevated token by default creates objects that are _owned_ to the `BUILTIN\Administrators` alias instead of the user — the un-elevated token by default will cause objects to be created as owned by `salvis` though. Explicitly setting the DACL inside the security descriptor (SD) would change those rules, but it would have to be done by Acronis or via PowerShell or programmatically. `subst` itself doesn't offer it.

There is another type of UAC elevation — called "over the shoulder" logon. This happens if the user `salvis` were _not_ a member of `BUILTIN\Administrators` (i.e. wouldn't have the option to elevate on their own), but an administrator would join that person and log on with the own admin credentials "over the shoulder". The difference is huge here, because in the latter case this affects all sorts of created objects in ways that most people will not desire.

PS: if you truly log on as `BUILTIN\Administrator` you will not even be subjected to elevation and by default run with your elevated token (unless that has changed at some point).
PPS: @NoMoreFood: Acronis is doing plenty crazy. I am sure `fltmc` run in an elevated Command Prompt will confirm it. IIRC they have a filter driver and probably also a shadow copy provider. May have changed in recent versions and depends on the features enabled in the product (there used to be something like a "continuous backup" years ago ...). ProcMon is probably the best way to see interactions with the underlying path, absent other kernel mode "agents".
¹ RID is relative ID and is the part of the user SID after the last dash

(again, I apologize for the technical detail and the nitpicking)

**Comment by assarbad** [comment] 2024-11-07 23:48
@NoMoreFood I don't know if it's worth it, but if you wanted to make these paths visible within WinDirStat you could query `TOKEN_LINKED_TOKEN` which gives the elevated token from unelevated context and vice versa (no linked token exists if elevation isn't supported for the current principal). Then you could access the respective contents of `\Sessions\0\DosDevices\%AUTHID%\X:` (for X == `A`..`Z`) — or enumerate everything that looks like a drive letter and is a symbolic link object — as outlined above after querying the authentication ID for the linked token. Feel free to "borrow" [relevant code](https://github.com/assarbad/ntobjx/blob/master/objmgr.hpp) from ntobjx into WinDirStat if it makes it easier to pull it off.

But I have my doubts that this will solve the particular issue presented here, since I suspect Acronis to play by its own rules by way of a file system filter. Since Windows 10 abandoned legacy file system filters, it stands to reason that the filter is visible via `fltmc`.

**Comment by NoMoreFood** [comment] 2024-11-08 14:10
@salvis I don't think it's the same issue, but I did see an issue where Acronis doesn't respond intelligently to GetVolumePathName() on an Acronis-mounted image.  I use this to function to help determine divide up the multithreaded queues.  I made a generalized accommodation that I would appreciate you trying.   I don't have a compatible phone to back up so I'm still working to try to reproduce that to reproduce your issue more precisely.

[WinDirStat.zip](https://github.com/user-attachments/files/17679697/WinDirStat.zip)

**Comment by NoMoreFood** [comment] 2024-11-12 01:17
@salvis 

Can you try the attached?  It appears like whatever the Acronis file system driver only handles a subset of the driver information classes.

[WinDirStat.zip](https://github.com/user-attachments/files/17709773/WinDirStat.zip)

**Comment by NoMoreFood** [comment] 2024-11-13 01:17
@salvis Any luck?

**Comment by salvis** [comment] 2024-11-13 13:45
Sorry for the delay, thanks for the nudge.

Yes, we can now open the subst'ed drive. However the stats on the Select Drive dialog are still wrong:

![image](https://github.com/user-attachments/assets/bab8de96-6e9f-48e2-90f1-8508f1ace456)

(I added an X: drive for testing.)

**Comment by NoMoreFood** [comment] 2024-11-13 13:56
Since those are volume-based statistics and those volumes point to the C: drive, they are accurate in that context.  Subst'd drives don't maintain a unique usage statistic we can rapidly query; you have to run a scan for that.  I don't think there's anything we can reasonably "fix" there.

**Comment by salvis** [comment] 2024-11-13 14:00
In that case maybe not display the stats at all? Just the drive letter and maybe the drive label, but no numbers and usage?

**Comment by salvis** [comment] 2024-11-13 14:03
I was really confused or even shocked at seeing that big drive F:, because I had actually forgotten about it.

**Comment by NoMoreFood** [comment] 2024-11-13 14:06
> In that case maybe not display the stats at all? Just the drive letter and maybe the drive label, but no numbers and usage?

That might reasonable.  I'll consider it if it doesn't complicate the code too much.

**Comment by salvis** [comment] 2024-11-13 14:14
Thanks!

**Comment by NoMoreFood** [comment] 2024-12-08 17:12
Released with https://github.com/windirstat/windirstat/releases/tag/release/v2.1.1

**Closed by NoMoreFood** 2024-12-08 17:12 UTC
Labels: bug, pending release
