### ISSUE TITLE
Duplicate Files Feature Not Working

### ISSUE THREAD

**Issue by nsummy** [windirstat/windirstat#110] opened 2024-10-23 16:38 UTC
I'm not sure if I am doing something wrong but checked all of the settings and didn't see anything obvious.  The Duplicate File Checked appears to do nothing.  I have even ran a rescan while the tab was open.  I noticed someone on Reddit also mentioned the same problem.  I am currently using this on the latest version of Windows 10 and upgraded from the 2.0 beta, if that matters.  Thanks!

**Comment by NoMoreFood** [comment] 2024-10-23 17:21
Definitely know it works, in general. So it must be something more nuanced.  Does it complete the scan, in general but just not show anything?  Can do a scan in a directory with a bunch of files you've copied/pasted (i.e. force some duplicates) and do a targeted folder scan to see wha
t it does?

**Comment by linuxgurugamer** [comment] 2024-10-23 17:31
For me, the scan works, shows me the disk layout.  I know I have a number of duplicated images in my Pictures directory, but nothing shows up in the duplicates tab.

There is no description of what it's supposed to do, would be helpful if there was documentation

**Comment by NoMoreFood** [comment] 2024-10-23 17:59
Can you go into PowerShell and run the following on the two files:

`Get-FileHash -Algorithm SHA512 -LiteralPath 'C:\Path\To\File.jpg'`

And see if the hashes on the files are differently.

**Comment by linuxgurugamer** [comment] 2024-10-23 18:48
I ran a script to get all the file hashes in this directory (Pictures).  Here are three files that are identical, with the hashes:

D:\Users\jbb\Pictures\7-3-2013\DSC00069 (1).JPG               00A2F73DF49A762258B8D42B76245648E4D8A6CE492D15D5D7C7F8C3961B0F9238BA053944293DAD9073546C9917CB4528033EC7FEE253F097D973816E8D56F0
D:\Users\jbb\Pictures\7-3-2013\DSC00069.JPG                   00A2F73DF49A762258B8D42B76245648E4D8A6CE492D15D5D7C7F8C3961B0F9238BA053944293DAD9073546C9917CB4528033EC7FEE253F097D973816E8D56F0
D:\Users\jbb\Pictures\Israel Trip\7-3-2013\DSC00069.JPG       00A2F73DF49A762258B8D42B76245648E4D8A6CE492D15D5D7C7F8C3961B0F9238BA053944293DAD9073546C9917CB4528033EC7FEE253F097D973816E8D56F0

**Comment by linuxgurugamer** [comment] 2024-10-23 18:49
There are lots more, i fyou need more examples, I can provide them

**Comment by NoMoreFood** [comment] 2024-10-23 19:33
Alright, so it's definitely a bug.  Can you tell me the file sizes or, if reasonable, email an example file to berns@uwalumni.com?

**Comment by linuxgurugamer** [comment] 2024-10-23 19:49
Directory: D:\Users\jbb\Pictures\7-3-2013


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          7/3/2013   2:53 PM        3801088 DSC00069.JPG

This is obviously one of many.  I'll send  this image to that email address

**Comment by NoMoreFood** [comment] 2024-10-23 20:05
Thanks!  I'll take a look tonight.  Their are various levels of size-checking and hashing that it does so it doesn't have to read every bit of every file so there must be some sort of logic hole it's falling into.

**Comment by NoMoreFood** [comment] 2024-10-23 23:28
@linuxgurugamer @nsummy No luck on reproducing thus far.  Two things to try (one at a time):

Under Advanced Options:

1. Uncheck 'Skip reading cloud links during duplicate detection'
2. Set 'Threads per drive' to '1'

**Comment by linuxgurugamer** [comment] 2024-10-27 00:00
> @linuxgurugamer @nsummy No luck on reproducing thus far. Two things to try (one at a time):
> 
> Under Advanced Options:
> 
> 1. Uncheck 'Skip reading cloud links during duplicate detection'.  If these files are being stored in OneDrive or something similar, the duplicate detection skips them so it doesn't pull them down if they aren't cached locally.
> 2. Set 'Threads per drive' to '1'.  If there's some sort of threading issue, this would help detect it.

Did that, no change.  Are there any log files I could send?
One think I forgot to mention, I have a number of drives, I've attached an image of them.  The only one I selected was drive D:
I don't think it matters, but figured I'd mention it

![drives](https://github.com/user-attachments/assets/f8db4585-3e19-419a-b51d-8ea6220a4bcc)

**Comment by georgir** [comment] 2024-10-27 11:12
did you check the checkbox at the bottom of your screenshot? :p
fwiw the duplicate files tab appears even with that checkbox potentially confusing some users, perhaps it should be hidden

**Comment by NoMoreFood** [comment] 2024-10-27 14:08
@georgir 

Thanks for chiming in. I was really struggling with why it might not have been working.

@linuxgurugamer 

I agree with disabling the tab (or hiding) it.  Surprisingly, it not super easy to do but it's probably worth it to avoid confusion.

**Comment by linuxgurugamer** [comment] 2024-10-27 14:37
Instead of disabling it, maybe put a message there (if the checkbox is not checked) that duplicate checking is disabled, and a messabe about how to enable it.  That would serve both the function of avoiding confusion and letting people know how to actually use it

**Comment by linuxgurugamer** [comment] 2024-10-27 14:47
So a question.  At what point do the number of threads not make a difference?

**Comment by linuxgurugamer** [comment] 2024-10-27 16:29
Not sure what the internal algorithm is for determining dups, but it seems that you are doing an SHA256 on the entire file.  Given that some systems have very large files, I wonder if the following might be faster:

1.  For all files under 64k, do the full sha256
2. For all files over 64k, do the sha256 on the first 64k only.  When the sha256 matches on files over 64k, then, on those files only, do the sha256 on the first 1 meg of the file.
3. If the sha256 on the first meg of the files match, then do the entire file

You might ever consider letting the user specify the size of the initial comparision..

This became apparent to me since my disk has been going for nearly 5 hours now, ajnd is only about 25% done (based on the physical size reported vs the disk space used)

**Comment by NoMoreFood** [comment] 2024-10-27 17:09
It's actually SHA512 which is faster than SHA256 (at least the Windows implementation). It does three phases: logical size, then a 128KiB hash, and then a full hash.  So similar to what you described, but with one less phase. I'll consider adding a fourth phase maybe even doing one at the end of the file which would probably be more fruitful than another one at the beginning.

It's been awhile since I unit tested it, but I'll double-check to make sure phasing logic is solid.

**Comment by NoMoreFood** [comment] 2024-10-27 17:16
> So a question. At what point do the number of threads not make a difference?

This is really hard to answer. For SSDs, maybe 4-8 threads.  For HDs, maybe 2-4 threads.  It's all a balance between how long it takes to seek to the data on the drive (knowing other threads are also competing to read chunks of data) and then the CPU required to compute the hash.  Keep in mind that thread changes only take effect on a new scan.

**Comment by NoMoreFood** [comment] 2024-11-02 23:23
Closing this since ultimately it was just a misunderstanding that you needed to enable the feature.  But I have added something to the beta release to inform the user that duplicate checking is not enabled when they click the tab.

**Closed by NoMoreFood** 2024-11-02 23:23 UTC
Labels: pending release
